export const meta = {
  slug: 'solar-payoff',
  name: 'Solar Panel Payoff Calculator',
  title: 'Solar Panel Payoff & ROI Calculator - Calcyx',
  description: 'Calculate the break-even period and 25-year financial return on investment (ROI) for installing solar panels.',
  category: 'everyday',
  icon: '☀️',
  keywords: ['solar panel', 'payoff period', 'break even', 'solar roi', 'electricity savings', 'green energy investment'],
  formula: 'Net Cost = System Cost - Incentives; Payoff is reached when Cumulative Savings >= Net Cost.',
  relatedSlugs: ['compound-interest', 'mortgage']
};

export function render() {
  const el = document.createElement('div');
  el.className = 'calc-page';

  el.innerHTML = `
    <div class="calc-card">
      <div class="calc-header">
        <span class="calc-icon">${meta.icon}</span>
        <h1 class="calc-title">${meta.name}</h1>
        <p class="calc-description">${meta.description}</p>
      </div>
      <div class="calc-body">
        <div class="calc-row">
          <div class="calc-input-group">
            <label for="system-cost">System Cost ($)</label>
            <input type="number" id="system-cost" class="calc-input" placeholder="e.g. 18000" step="100" min="0" value="18000">
          </div>
          <div class="calc-input-group">
            <label for="incentives">Tax Incentives / Rebates ($)</label>
            <input type="number" id="incentives" class="calc-input" placeholder="e.g. 5400" step="100" min="0" value="5400">
          </div>
        </div>

        <div class="calc-row">
          <div class="calc-input-group">
            <label for="monthly-bill">Avg Monthly Power Bill ($)</label>
            <input type="number" id="monthly-bill" class="calc-input" placeholder="e.g. 150" step="5" min="0" value="150">
          </div>
          <div class="calc-input-group">
            <label for="cover-ratio">Solar Bill Offset (%)</label>
            <input type="number" id="cover-ratio" class="calc-input" placeholder="e.g. 90" step="1" min="0" max="100" value="90">
          </div>
        </div>

        <div class="calc-input-group">
          <label for="inflation-rate">Annual Electricity Inflation (%)</label>
          <input type="number" id="inflation-rate" class="calc-input" placeholder="e.g. 4.0" step="0.1" min="0" max="50" value="4.0">
        </div>

        <div id="result" class="calc-result" style="display: none;">
          <div class="calc-result-value" id="payoff-period-val">8.2 Years</div>
          <div class="calc-result-label">Payoff Period (Break-Even)</div>
          
          <div class="calc-result-grid" style="margin-top: 1.5rem;">
            <div class="calc-result-item">
              <div class="calc-result-value" id="net-cost-val">$12,600</div>
              <div class="calc-result-label">Net System Cost</div>
            </div>
            <div class="calc-result-item">
              <div class="calc-result-value" id="year1-savings-val">$1,620</div>
              <div class="calc-result-label">Year 1 Savings</div>
            </div>
            <div class="calc-result-item">
              <div class="calc-result-value" id="savings-25-val">$58,200</div>
              <div class="calc-result-label">25-Yr Total Savings</div>
            </div>
            <div class="calc-result-item">
              <div class="calc-result-value" id="roi-25-val">362%</div>
              <div class="calc-result-label">25-Yr ROI (Profit: $45,600)</div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="calc-formula">
        <h3>☀️ Solar Investment Financial Formulas</h3>
        <p>1. <strong>Net System Cost:</strong> The upfront cost of installing the panels minus any tax credits, utility rebates, or government incentives.</p>
        <code>Net Cost = System Cost - Incentives</code>
        <p>2. <strong>Yearly Savings:</strong> Calculated based on your monthly utility bill, the cover ratio (percentage of power generated by solar), and compounded annually by electricity inflation.</p>
        <code>Savings(Year n) = (Monthly Bill × Cover Ratio × 12) × (1 + Inflation)ⁿ⁻¹</code>
        <p>3. <strong>Payoff Period:</strong> The exact year when cumulative electricity savings equal or exceed the net system cost.</p>
        <p>4. <strong>25-Year ROI:</strong> Solar panels typically have a warranty and lifespan of 25 years. This tracks the total profit and return on investment over that lifetime.</p>
      </div>
    </div>
  `;
  return el;
}

export function mount() {
  const systemCostInput = document.getElementById('system-cost');
  const incentivesInput = document.getElementById('incentives');
  const monthlyBillInput = document.getElementById('monthly-bill');
  const coverRatioInput = document.getElementById('cover-ratio');
  const inflationRateInput = document.getElementById('inflation-rate');

  const resultDiv = document.getElementById('result');
  const payoffPeriodVal = document.getElementById('payoff-period-val');
  const netCostVal = document.getElementById('net-cost-val');
  const year1SavingsVal = document.getElementById('year1-savings-val');
  const savings25Val = document.getElementById('savings-25-val');
  const roi25Val = document.getElementById('roi-25-val');

  function calculate() {
    const systemCost = parseFloat(systemCostInput.value);
    const incentives = parseFloat(incentivesInput.value) || 0;
    const monthlyBill = parseFloat(monthlyBillInput.value);
    const coverRatio = parseFloat(coverRatioInput.value);
    const inflationRate = parseFloat(inflationRateInput.value) || 0;

    if (isNaN(systemCost) || isNaN(monthlyBill) || isNaN(coverRatio) ||
        systemCost < 0 || monthlyBill < 0 || coverRatio < 0 || coverRatio > 100 || inflationRate < 0) {
      resultDiv.style.display = 'none';
      return;
    }

    const netCost = Math.max(0, systemCost - incentives);
    const initialMonthlySavings = monthlyBill * (coverRatio / 100);
    const year1Savings = initialMonthlySavings * 12;

    if (year1Savings <= 0) {
      // If there are no savings, payoff is impossible unless cost is 0
      if (netCost === 0) {
        payoffPeriodVal.textContent = '0.0 Years';
        netCostVal.textContent = '$0';
        year1SavingsVal.textContent = '$0';
        savings25Val.textContent = '$0';
        roi25Val.textContent = '0%';
        resultDiv.style.display = 'block';
      } else {
        resultDiv.style.display = 'none';
      }
      return;
    }

    // Payoff period calculation (year-by-year with fraction)
    let cumulativeSavings = 0;
    let currentYearSavings = year1Savings;
    let payoffYears = null;
    const maxYears = 100;

    for (let year = 1; year <= maxYears; year++) {
      const remainingCost = netCost - cumulativeSavings;
      if (currentYearSavings >= remainingCost) {
        payoffYears = (year - 1) + (remainingCost / currentYearSavings);
        break;
      }
      cumulativeSavings += currentYearSavings;
      currentYearSavings *= (1 + inflationRate / 100);
    }

    // 25-Year ROI calculation
    let totalSavings25 = 0;
    let activeSavings = year1Savings;
    for (let year = 1; year <= 25; year++) {
      totalSavings25 += activeSavings;
      activeSavings *= (1 + inflationRate / 100);
    }

    const netProfit25 = totalSavings25 - netCost;
    const roiPercent25 = netCost > 0 ? (netProfit25 / netCost) * 100 : 0;

    // Format output
    netCostVal.textContent = `$${Math.round(netCost).toLocaleString()}`;
    year1SavingsVal.textContent = `$${Math.round(year1Savings).toLocaleString()}`;
    savings25Val.textContent = `$${Math.round(totalSavings25).toLocaleString()}`;

    if (payoffYears !== null) {
      payoffPeriodVal.textContent = `${payoffYears.toFixed(1)} Year${payoffYears.toFixed(1) !== '1.0' ? 's' : ''}`;
    } else {
      payoffPeriodVal.textContent = '100+ Years';
    }

    const profitStr = netProfit25 >= 0 
      ? `Profit: $${Math.round(netProfit25).toLocaleString()}`
      : `Net Loss: $${Math.round(Math.abs(netProfit25)).toLocaleString()}`;
    
    roi25Val.textContent = `${netCost > 0 ? Math.round(roiPercent25) : 0}% (${profitStr})`;

    resultDiv.style.display = 'block';
  }

  // Event Listeners
  systemCostInput.addEventListener('input', calculate);
  incentivesInput.addEventListener('input', calculate);
  monthlyBillInput.addEventListener('input', calculate);
  coverRatioInput.addEventListener('input', calculate);
  inflationRateInput.addEventListener('input', calculate);

  // Initialize
  calculate();

  return () => {
    systemCostInput.removeEventListener('input', calculate);
    incentivesInput.removeEventListener('input', calculate);
    monthlyBillInput.removeEventListener('input', calculate);
    coverRatioInput.removeEventListener('input', calculate);
    inflationRateInput.removeEventListener('input', calculate);
  };
}
